# Generated by Django 5.0.2 on 2024-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_account_id_customuser_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.IntegerField()),
                ("role_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("active_status_id", models.IntegerField()),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
