# Generated by Django 5.0.2 on 2024-03-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_invitation_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="groups",),
    ]
