# Generated by Django 5.0.2 on 2024-03-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_customuser_groups"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="user_permissions",),
    ]
